#For local environment deployment
server:
  port: 9091
  servlet:
    context-path: /images 

spring:
  profiles : local
  application:
    name: image-processing-app 
   
#  data:
#    mongodb:
#      host: localhost
#      database: images
#      port: 27017
#      repositories:
#        type: auto
        
logging:
  level:
    org.springframework: DEBUG
    com.diatoz: TRACE
        
---
# For heroku environment deployment     
server:
  port: ${PORT:9091}
  servlet:
    context-path: /images
spring:
  profiles: heroku
  application:
    name: image-processing-app  
#  data:
#    mongodb:
#      uri: mongodb://developer:1Developer@meshcluster-shard-00-00-ca4vj.mongodb.net:27017,meshcluster-shard-00-01-ca4vj.mongodb.net:27017,meshcluster-shard-00-02-ca4vj.mongodb.net:27017/diatoz?ssl=true&replicaSet=meshcluster-shard-0&authSource=admin
      
logging:
  level:
    org.springframework: TRACE
    com.diatoz: TRACE
        